version: '3.8'

services:
  mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile.production
    container_name: production-mcp-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data:ro
      - ./logs:/var/log/mcp-server
      - ./ssl:/etc/ssl/certs:ro
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}
      - LOG_LEVEL=INFO
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "python /app/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Optional: Reverse proxy with SSL termination
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - mcp-server
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge