services:
  rest-api-mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_rest_api/Dockerfile
    container_name: rest-api-mcp-server
    restart: unless-stopped
    ports:
      - "0.0.0.0:3004:3004"
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_AUTH_TOKEN=
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MCP_PORT=3004
      - RESUME_API_URL=${RESUME_API_URL:-http://dev01.int.stortz.tech:8002}
    env_file:
      - .env
    volumes:
      - ../../src:/app/src:ro
      - ../../logs:/app/logs
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import asyncio; from src.mcp_rest_api.__main__ import main; asyncio.run(main())'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  mcp-network:
    driver: bridge
