services:
  postgres-mcp:
    build:
      context: ../..
      dockerfile: docker/mcp_postgres/Dockerfile
    container_name: postgres-mcp-server
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN:-}
      - DATABASE_WS_URL=${DATABASE_WS_URL:-http://dev01.int.stortz.tech:8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import asyncio; from src.mcp_postgres.__main__ import main; asyncio.run(main())'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  mcp-network:
    driver: bridge
