server:
  host: "0.0.0.0"
  port: 3001
  
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  database: "postgres"
  username: "postgres"
  password: "${POSTGRES_PASSWORD}"
  ssl_mode: "prefer"

database_service:
  url: "http://dev01.int.stortz.tech:8000"
  timeout: 30
  retry_attempts: 3
  
security:
  auth_enabled: true
  auth_token: "${MCP_AUTH_TOKEN}"
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  
rate_limiting:
  requests_per_minute: 100
  window_seconds: 60
  
limits:
  max_connections: 50
  request_timeout: 300
  max_file_size: 1048576
  
logging:
  level: "INFO"
  file: "postgres_mcp_server.log"
  format: "json"
