server:
  host: "0.0.0.0"
  port: 3003
  
database:
  type: "redis"
  host: "localhost"
  port: 6379
  database: 0
  password: "${REDIS_PASSWORD}"
  
security:
  auth_enabled: true
  auth_token: "${MCP_AUTH_TOKEN}"
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  
rate_limiting:
  requests_per_minute: 100
  window_seconds: 60
  
limits:
  max_connections: 50
  request_timeout: 300
  max_file_size: 1048576
  
logging:
  level: "INFO"
  file: "redis_mcp_server.log"
  format: "json"
