server:
  host: "0.0.0.0"
  port: 3002
  
database:
  type: "mysql"
  host: "localhost"
  port: 3306
  database: "mysql"
  username: "root"
  password: "${MYSQL_PASSWORD}"
  ssl_mode: "prefer"
  
security:
  auth_enabled: true
  auth_token: "${MCP_AUTH_TOKEN}"
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  
rate_limiting:
  requests_per_minute: 100
  window_seconds: 60
  
limits:
  max_connections: 50
  request_timeout: 300
  max_file_size: 1048576
  
logging:
  level: "INFO"
  file: "mysql_mcp_server.log"
  format: "json"
